// Offline service worker. GENERATED by tools/build.py from tools/templates/sw.js.
// Never hand-edit sw.js: the cache name carries a content hash, so every
// change to the shell or the data produces a new cache automatically.
const CACHE = '__CACHE__';
const KEY = '__KEY__';
const SHELL = __SHELL__;
const STATIC = __STATIC__;

// GitHub Pages lets a browser keep every file for 10 minutes (max-age=600), so
// in the minutes after a deploy its HTTP cache still holds the old files. The
// precache goes past that cache ('reload'), and the shell is always checked
// with the server ('no-cache': a 304 when nothing changed), or a new worker
// stores the old files under its new name and the page mixes two builds
// (found by the first in-place migration's upgrade proof, 8 Oct).
self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(SHELL.concat(STATIC).map(u => new Request(u, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
  );
});

// Every tracker on the same origin (e.g. one GitHub Pages user site) shares one
// cache storage, so only this tracker's own earlier caches are removed:
// <key>-v<N> (template v2) and <key>-<12 hex> (v3). Another tracker's caches,
// and anything else, are left alone.
function ownOld(k) {
  return k !== CACHE && k.indexOf(KEY + '-') === 0 && /^(v\d+|[0-9a-f]{12})$/.test(k.slice(KEY.length + 1));
}

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(ownOld).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function isShell(url) {
  return SHELL.some(p => (p === './' ? url.pathname.endsWith('/') : url.pathname.endsWith(p.slice(1))));
}

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (isShell(url)) {
    // network-first: a deploy reaches the device on the next plain reload
    e.respondWith(
      fetch(e.request, { cache: 'no-cache' }).then(res => {
        if (res && res.status === 200) {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, copy));
        }
        return res;
      }).catch(() => caches.match(e.request)
        .then(hit => hit || caches.match('./index.html'))
        .then(hit => hit || new Response('Offline and not cached yet.', { status: 503 })))
    );
    return;
  }
  // fonts and icons: cache-first
  e.respondWith(
    caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {
      if (res && res.status === 200 && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
      }
      return res;
    }).catch(() => new Response('', { status: 504 })))
  );
});
