// Offline service worker. GENERATED by tools/build.py from tools/templates/sw.js.
// Never hand-edit sw.js: the cache name carries a content hash, so every
// change to the shell or the data produces a new cache automatically.
const CACHE = '__CACHE__';
const SHELL = __SHELL__;
const STATIC = __STATIC__;

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(SHELL.concat(STATIC)))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function isShell(url) {
  return SHELL.some(p => (p === './' ? url.pathname.endsWith('/') : url.pathname.endsWith(p.slice(1))));
}

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (isShell(url)) {
    // network-first: a deploy reaches the device on the next plain reload
    e.respondWith(
      fetch(e.request).then(res => {
        if (res && res.status === 200) {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, copy));
        }
        return res;
      }).catch(() => caches.match(e.request)
        .then(hit => hit || caches.match('./index.html'))
        .then(hit => hit || new Response('Offline and not cached yet.', { status: 503 })))
    );
    return;
  }
  // fonts and icons: cache-first
  e.respondWith(
    caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {
      if (res && res.status === 200 && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
      }
      return res;
    }).catch(() => new Response('', { status: 504 })))
  );
});
